embassy-rs/chiptool

src/generate/block.rs, src/generate/common.rs, src/generate/fieldset.rs
It dramatically reduces the build size and improve performance, especially when using `opt-level = "z"`
Take the following function, writing repeatedly to the SPI device:
```rust
pub unsafe fn spi_write_repeated(&mut self, data: u16, count: usize) {
for _ in 0..count {
let regs = embassy_stm32::pac::SPI1;
while !regs.sr().read().txe() {}
regs.dr().write(|w| w.set_dr(data));
}
}     
```
With `opt-level = "z"`, it compiles to the following (I've added some labels for better readability)
```
0802bc44 <spi_write_repeated>:
802bc44: f0 b5        	push	{r4, r5, r6, r7, lr}
802bc46: 03 af        	add	r7, sp, #12
802bc48: 2d e9 f0 07  	push.w	{r4, r5, r6, r7, r8, r9, r10}
802bc4c: 0f 4d        	ldr	r5, [pc, #60]           @ 0x802bc8c <$d.52>
802bc4e: 0d f1 0c 08  	add.w	r8, sp, #12
802bc52: 27 …
```
=> Always inline access to registers

src/generate/device.rs, src/ir.rs, src/svd2ir.rs
The intention is to regenerate `stm32-metapac` crate,  to include interrupt definitions, similar to those in peripheral access crates that are based on `svd2rust`, so that the `embassy-stm32` HAL can be used in an [RTIC](https://github.com/rtic-rs/rtic) application.
With current functionality, it is possible to do this in an RTIC app - thanks to @korken89 and @MathiasKoch for the pointers :
```rust
pub mod pac {
pub const NVIC_PRIO_BITS: u8 = 2;
pub use cortex_m_rt::interrupt;
pub use embassy_stm32::pac::Interrupt as interrupt;
pub use embassy_stm32::pac::*;
}
#[app(device = crate::pac, peripherals = false)]
```
The intention would be to reduce it to:
```rust
#[app(device = embassy_stm32, peripherals = false)]
```
[x] Expose `interrupt` attribute macro, `Interrupt` enum. (This was the …
=> Add missing interrupt definitions so that generated pac's can be used in an RTIC application

Cargo.lock, Cargo.toml, src/main.rs, src/svd2ir.rs
This uses the register properties to the register bit size.
This updates `svd-parser` to version 0.14.2 in order to use the `expand` feature, specifically the `expand_properties` configuration. An alternate method would be to effectively do the expansion in `chiptool` instead, but I don't see the reason to do this.
=> Register Properties

src/transform/common.rs, src/transform/delete_enums.rs, src/transform/merge_enums.rs
concat variant descriptions of a enum, then append to related field description
take a look at embassy-rs/stm32-data#358 for a example
=> add `keep_desc` option to `DeleteEnums` and `MergeEnums` transform

src/generate/fieldset.rs, src/ir.rs, src/svd2ir.rs, src/transform/delete_fieldsets.rs, src/transform/make_field_array.rs, src/transform/sort.rs, src/validate.rs
I found some "discontinuous field" when I make timer_v2.
eg. 
`MMS` of `TIMx_CR2` from Page1567 of Section38 AdvTim of H573 [RM0481];
`TS` of `TIMx_SMCR` from the same page.
I try add support for this situation.
------
yaml file will support
```yaml
fieldset/CR2_2CH_CMP:
extends: CR2_1CH_CMP
description: control register 2
fields:
- name: MMS
description: Master mode selection
bit_offset:
- start: 4
end: 6
- start: 25
end: 25
bit_size: 4
enum: MMS
```
new syntax, and chiptool do properly check when parse source file.
It will generate PAC like this:
```rust
#[doc = "Master mode selection"]
#[inline(always)]
pub const fn mms(&self) -> super::vals::Mms {
let mut val = 0;
val += (((self.0 >> 4usize) & 0x07) << 0usize);
val += (((self.0 >> 25usize) & 0x01) << 3usize); …
```
=> Support discontinuous field

src/transform/modify_byte_offset.rs
allow something like this:
```yaml
transforms:
- !ModifyByteOffset
blocks: ADC_COMMON
exclude_items: ^CDR$
add_offset: -768 # 0x300
```
can output errors (when use with `strict: true` and do a rerun) like this:
```text
thread 'main' panicked at src/transform/modify_byte_offset.rs:48:13:
Block: ADC_COMMON Item: CSR: byte_offset out of range after modify
Block: ADC_COMMON Item: CCR: byte_offset out of range after modify
Block: ADC_COMMON Item: HWCFGR0: byte_offset out of range after modify
Block: ADC_COMMON Item: VERR: byte_offset out of range after modify
Block: ADC_COMMON Item: IPDR: byte_offset out of range after modify
Block: ADC_COMMON Item: SIDR: byte_offset out of range after modify
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Notice:
value range …
=> allow negative byte offset

Cargo.lock, Cargo.toml, README.md, rust-toolchain.toml
Mainly to address #37, but misc other nitpicks.
=> Switch `rust-toolchain.toml` to latest stable

src/transform/delete_peripherals.rs, src/transform/mod.rs
Add `DeletePeripherals` transform to delete peripherals from specific devices. This will not delete related blocks, regs and vals.
```yaml
transforms:
- !DeletePeripherals
devices: .*
from: PORT
```
=> Add DeletePeripherals.

src/main.rs
This PR implement a `includes` in transforms.
`includes` and `transforms` can be empty. Files list in `includes` are related to current yaml file.
This design is compatible.
Example:
```yaml
includes:
- peripheral_a.yaml
transforms:
- ...
```
```yaml
transforms:
- ...
```
=> Add includes to Config.

src/generate/device.rs, src/generate/enumm.rs, src/generate/fieldset.rs, src/generate/mod.rs, src/ir.rs, src/main.rs, src/svd2ir.rs, src/transform/fix_register_bit_sizes.rs, src/transform/mod.rs
This PR:
* Implements the `Debug` and `defmt::Format` traits for generated fieldsets, value enums and interrupt enums.
* Where possible the traits are simply derived.
* The `defmt::Format` impls are disabled by default and must be enabled with a `"defmt"` feature.
* Re-adds the `expand_extends` transform which I think was accidentally removed during a refactor of the transform system (couldn't test this with the `stm32-metapac` crate otherwise).
* Fixes some clippy warnings.
I think the `Debug` and `defmt::Format` impls can help tremendously when debugging embedded applications :)
I've tested this by using it to regenerate the `stm32-metapac` crate, which added the trait impls as expected. I've also tested that the generated code compiles and looks as as expected.
=> Implement Debug and defmt::Format for fieldsets, enums and the interrupt enum.

src/transform/rename.rs
```yaml
- !Rename
from: (.*)
to: regs::$1
type: Fieldset
```
This is helpful to move all registers or enums into a separate module.
=> Update Rename to allow type selection.

src/transform/delete_fields.rs, src/transform/mod.rs
Add `DeleteFields` transform.
example:
``` yaml
- !DeleteFields
fieldset: .*
from: rsvd.*
```
I have checked the available transforms, but I couldn't find one that implements this functionality. If such a transform already exists, I will close this PR.
=> Add `DeleteFields` transform

src/transform/add_interrupts.rs, src/transform/mod.rs
Add `AddInterrupts` transform.
example:
``` yaml
- !AddInterrupts
devices: .*
interrupts:
- name: I2C1_IRQ
value: 10
description: I2C1 interrupt
- name: I2C2_IRQ
value: 11
description: I2C2 interrupt
```
Although some modifications in [svd2ir.rs](https://github.com/embassy-rs/chiptool/blob/main/src/svd2ir.rs) would allow the use of the `Add` transform to add device interrupts, the `Add` transform merges at the `Vec<Device>` level, which results in interrupts and peripherals being overwritten. Therefore, I have added the `AddInterrupts` transform.
=> Add `AddInterrupts` transform

src/transform/delete_useless_enums.rs
These enum variants appear in the MSPM0 SVD files.
Examples:
```yaml
enum/ICLR_SYSPLLGOOD:
bit_size: 1
variants:
- name: NO_EFFECT
value: 0
- name: CLR
value: 1
enum/ISET_BORLVL:
bit_size: 1
variants:
- name: NO_EFFECT
value: 0
- name: SET
value: 1
```
=> Add no_effect, clr and set to DeleteUselessEnums

src/transform/delete_useless_enums.rs
The MSPM0 SVDs sometimes use `PASSTHRU` as the zero value for a useless enum.
Example:
```yaml
enum/EXCLKDIVEN:
bit_size: 1
variants:
- name: PASSTHRU
value: 0
- name: ENABLE
value: 1
```
=> Add passthru to DeleteUselessEnums

src/transform/delete_enum_variants.rs, src/transform/mod.rs
Add `DeleteEnumVariants` transform. This exists because the SVDs for the MSPM0C110x contain enum variants which do not exist on the part.
The transform just removes variants which match. 
Example:
```yaml
- !DeleteEnumVariants
enum: (SYSOSCCFG_FREQ|SYSOSCFREQ)
from: SYSOSCTURBO
```
Resolves #56
=> Add DeleteEnumVariants transform

src/transform/mod.rs, src/transform/resize_enums.rs
The MSPM0 SVDs have enums which are larger than needed. An example of this is the `STAT` register for the MSPM0C110x where after eliminating variants not present in the technical manual manual (see #58), there are 2 bits of unused space which are reserved.
Example:
```yaml
- !ResizeEnums
enum: STAT
bit_size: 2
```
Along side resizing the enum, uses of the enum have the bit size changed as well. The transform also validates the following:
- The new size is not 0 (why would you do this?)
- That the enum variants can be represented in the range of valid values for the bit size (e.g., no value of 4 for a 2-bit enum with a maximum value of 3)
- If the enum has grown in size, that no field overlaps are created as a result of the resize.
=> Add ResizeEnums transform

src/ir.rs
Currently, chiptool generated PAC are missing top level peripherals and interrupt
definitions when used from a pure YAML workflow, i.e. without an SVD file, as in
the following command:
`chiptool gen-block --input xmc4800.yml --output src/lib.rs`
Such an approach is useful if no well-written SVD file is available for
the target MCU. For example, the XMC4800 SVD file calls all enumerated values
`value1`, `value2` and so on resulting in a de-facto unusable PAC.
Since all IR already implements `Serialize` and `Deserialize` traits,
this workflow is enabled by reading/writing the IR `Device` block
from/to YAML as well as done in the PR.
A minimum working YAML looks like:
```
---
device/:
nvic_priority_bits: 4
peripherals:
- name: SCU
description: System Control Unit
base_address: 0x50004000 …
```
=> Enable pure YAML based workflow

src/transform/mod.rs, src/transform/modify_fields_enum.rs
Allows modifying a field's `enum` by binding the field to a specific enum.
We can also use `Add` and `ModifyFieldsEnum` to add an enum:
``` yaml
- !Add
ir:
enum/rcc::vals::SelSys:
bit_size: 2
variants:
- name: HSI
value: 0
- name: HSE
value: 1
- name: PLL
value: 2
- !ModifyFieldsEnum
fieldset: rcc::regs::Dwcfgr
field: sel_sys
enum: rcc::vals::SelSys
```
=> Add `ModifyFieldsEnum` transform

Cargo.lock, Cargo.toml
After merging PR 1, svd-parser can parse SVDs without fpuPresent attributes. Update chiptool to latest parser so it can be used to extract peripherals from such SVD files.
=> Update svd-parser revision

src/generate/fieldset.rs
Since `&mut` is allowed since a few releases, this makes all setters `const fn`.
=> Make setters const fn

src/generate/common.rs, src/generate/fieldset.rs
This changes the `write` and `modify` API slightly such that one can get proper warnings when accidentally having the return value support hide that the write is not used.
From what I found by looking around I did not really see any use of the return value.
=> Make wrong use of write/modify give warnings

src/transform/mod.rs, src/transform/modify_registers.rs
This enables setting the fieldsets of registers if they are missing from the SVD.
I made it a generic "ModifyRegisters" transform because if somebody needs to change e.g. the accessibility of a register later, it could be added. Added to fix some DMA register aliases in `rp-pac` which do not have field information at all in the SVD, but simply alias the corresponding main registers so the same fieldset can be reused.
Works like this:
```yaml
- !MakeBlock
blocks: dma::Dma
from: ch(\d+)_(.*)
to_block: dma::Channel
to_outer: ch$1
to_inner: $2
- !ModifyRegisters
blocks: dma::Channel
registers: al\d_ctrl
fieldset: dma::regs::CtrlTrig
```
=> Add ModifyRegisters transform

src/generate/device.rs, src/generate/enumm.rs, src/generate/fieldset.rs, src/generate/mod.rs, src/main.rs
This PR implements three different options for `defmt` support in generated code:
- `DefmtOption::Disabled`: code that implements `defmt::Display` is not included in the generated code (as already implemented).
- `DefmtOption::Feature(feature)`: code for `defmt::Display` is gated behind a feature with given name (as already implemented).
- `DefmtOption::Enabled`: code for `defmt::Display` is included unconditionally (this option is new).
This is a breaking change in the API but backward compatible change in the CLI interface. I also added a CLI option `--yes-defmt` which corresponds to `DefmtOption::Enabled` (the opposite of `--no-defmt`, which maps to `DefmtOption::Disabled`).
This is useful when you want to include some code generated by `chiptool` into a larger crate where `defmt` is …
=> Add an option to generate `defmt` support unconditionally

Cargo.lock, src/generate/block.rs
pointer::add on provenance-less pointers is unsound. The wrapping version is more tolerant.
The lockfile automatically updates, as it has diverged from the version specified in the TOML file. I split it into a separate commit in case you want to discard it.
I tested these changes by regenerating and cargo checking rp-pac using the script in that repo
Please let me know if anything else is needed
=> Use pointer wrapping add
